// Immediately invoked function expration (IIFE).

// we just prepare the iife function we don't need to call the function.
// syntax is : (
// function(){
//       statements......
//            }
// )
// (); // function calling.


(
    function(name,DOB,mobailnumber)
    {
         let detiles = "my detailes";
    console.log(detiles);
console.log(name);
console.log(DOB);
console.log(mobailnumber);
  }
)("Raju","1900.10.04","970xxx0x71");

/// in this function we don't need to call the function .
// in the iffi function we only call anonymous function only.
